### ISSUE TITLE
"Go To Declaration" shows WARN with TimeoutException and stack trace 

### ISSUE THREAD

**Issue by KUGDev** [redhat-developer/lsp4ij#377] opened 2024-06-20 11:55 UTC
The plugin to test the behaviour: https://github.com/zowe/zowe-cobol-language-support-intellij
There is [demo.cbl](https://github.com/zowe/zowe-cobol-language-support-intellij/blob/main/src/main/resources/demo.cbl) file to test the issue when the plugin is installed.
Tested with 0.0.2-20240620-013214

When the LSP server is not yet fully initialized, trying to trigger "Go To Declaration" by Ctrl/Cmd + click results in WARN with exception, shown below

```
2024-06-20 13:48:49,161 [  69300]   WARN - com.redhat.devtools.lsp4ij.features.navigation.LSPGotoDeclarationHandler - null
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at com.redhat.devtools.lsp4ij.features.navigation.LSPGotoDeclarationHandler.getGotoDeclarationTargets(LSPGotoDeclarationHandler.java:72)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.fromGTDProvidersInner$lambda$0(gtdProviders.kt:38)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:637)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:55)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.fromGTDProvidersInner(gtdProviders.kt:35)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.access$fromGTDProvidersInner(gtdProviders.kt:1)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt$fromGTDProviders$1.invoke(gtdProviders.kt:22)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt$fromGTDProviders$1.invoke(gtdProviders.kt:21)
	at com.intellij.codeInsight.navigation.impl.CommonKt.processInjectionThenHost(common.kt:29)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.fromGTDProviders(gtdProviders.kt:21)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.gotoDeclarationOrUsages(GotoDeclarationOrUsageHandler2.kt:35)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.invoke$lambda$0(GotoDeclarationOrUsageHandler2.kt:58)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.underModalProgress$lambda$1(ActionUtil.kt:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.underModalProgress$lambda$2(ActionUtil.kt:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:299)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:567)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:86)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by fbricon** [comment] 2024-06-20 13:43
I tried your plugin, but I guess my laptop is too fast, the Cobol LS starts so rapidly I can't reproduce this issue

**Comment by fbricon** [comment] 2024-06-20 13:45
Does an error pops up or is it just a warning in the logs?

**Comment by KUGDev** [comment] 2024-06-20 13:46
Only logs

**Comment by angelozerr** [comment] 2024-06-20 13:52
Devant l ecole?

Le jeu. 20 juin 2024 à 3:47 PM, Uladzislau ***@***.***> a
écrit :

**Comment by angelozerr** [comment] 2024-06-20 14:04
We need to try to remove this timeout

**Comment by angelozerr** [comment] 2024-06-20 14:06
Oops sorry @KUGDev  I removed your comment when you said

Only logs

**Comment by angelozerr** [comment] 2024-09-30 13:42
fixed with https://github.com/redhat-developer/lsp4ij/pull/551

**Closed by angelozerr** 2024-09-30 13:42 UTC
Labels: bug, declaration
