### ISSUE TITLE
Feature request: A way for languages or language servers to bypass the canFormat check

### ISSUE THREAD

**Issue by FalsePattern** [redhat-developer/lsp4ij#424] opened 2024-07-17 12:34 UTC
In AbstractLSPFormattingService, `canFormat` checks for the presence of a LanguageFormatting implementation for a language, and if present, doesn't invoke the LSP formatter.

In the case of ZigBrains, I used both the LSP formatter for manual formatting via ZLS when invoking the formatting action, as well as the intellij autoformatter for correct auto-indentation when creating new lines or code blocks. If the zigbrains `lang.formatter` is removed, auto-indentation breaks, but the ZLS formatter functions.

**Comment by angelozerr** [comment] 2024-07-17 13:05
Same issue than https://github.com/redhat-developer/lsp4ij/issues/388

**Comment by angelozerr** [comment] 2024-10-02 14:15
Duplicate of https://github.com/redhat-developer/lsp4ij/issues/388 and covered with the current PR https://github.com/redhat-developer/lsp4ij/pull/543

**Closed by angelozerr** 2024-10-02 14:15 UTC
Labels: duplicate, enhancement, formatting, api-customization
