### ISSUE TITLE
Two `textDocument/didChange` events being sent in Goland

### ISSUE THREAD

**Issue by rcjsuen** [redhat-developer/lsp4ij#583] opened 2024-10-24 22:24 UTC
I'm assuming I'm doing something wrong...because I feel like someone else would have filed this bug already. What's interesting is...
- the version numbers differ
- the `uri` has the absolute path and then just the file name...?
- the `contentChanges` are identical

Note that I am using `TextDocumentSyncKind.Full` (which is equivalent to `1` from what I can tell).
```JSONC
[Trace - 18:20:40] Sending notification 'textDocument/didChange'
Params: {
  "textDocument": {
    "version": 14,
    "uri": "file:///Users/rcjsuen/abc.xyz"
  },
  "contentChanges": [
    {
      "text": "same thing"
    }
  ]
}
```
```JSONC
[Trace - 18:20:40] Sending notification 'textDocument/didChange'
Params: {
  "textDocument": {
    "version": 15,
    "uri": "file:///abc.xyz"
  },
  "contentChanges": [
    {
      "text": "same thing"
    }
  ]
}
```

**Comment by angelozerr** [comment] 2024-10-26 05:38
You mean that you have registered a language server with lsp4ij and you have this kind of lsp didChange notifications?

If it is that it is very strange. Could you tell me which ls you are starting and give me some explanation how to start it please.

Thanks

**Comment by angelozerr** [comment] 2024-10-26 05:40
> You mean that you have registered a language server with lsp4ij and you have this kind of lsp didChange notifications?
> 
> If it is that it is very strange. Could you tell me which ls you are starting and give me some explanation how to start it please.
> 
> Thanks

I have never tested a language server with text full synchronization, perhaps there is a bug with this synch kind?

**Comment by rcjsuen** [comment] 2024-10-26 23:02
> You mean that you have registered a language server with lsp4ij and you have this kind of lsp didChange notifications?

Correct. I am pasting stuff from the "Traces" view.

> If it is that it is very strange. Could you tell me which ls you are starting and give me some explanation how to start it please.

Sorry, I am unable to share details about the language server I am using.

Here is something else I noticed.

In the `initialize` message from the client, I see `{ "rootUri": null, "workspaceFolders": [] }` when I have GoLand opened to a project. The background is brown though which suggests to me the IDE has gotten into some [strange state](https://stackoverflow.com/questions/74246045/phpstorm-set-all-files-folders-to-brown-background-and-weird-structure).

<img width="104" alt="image" src="https://github.com/user-attachments/assets/8269b2a1-70a8-459f-aab1-27c52f9409ed">

I think this is likely the root cause of the issue...? Probably? The IDE seems to know I have a file opened at the full path but also since it's "not really in a project" perhaps it cannot (or does not try to) do any path resolution and also seems to think I have a file opened "nowhere" and hence just has it at `file:///`?

**Comment by rcjsuen** [comment] 2024-10-26 23:07
> I have never tested a language server with text full synchronization, perhaps there is a bug with this synch kind?

I changed the code to use `TextDocumentSyncKind.Incremental` (and I can see the value of `2` in the logs) and it still happens so we can probably rule that out. 👍

**Comment by angelozerr** [comment] 2024-10-26 23:13
> > You mean that you have registered a language server with lsp4ij and you have this kind of lsp didChange notifications?
> 
> Correct. I am pasting stuff from the "Traces" view.
> 
> > If it is that it is very strange. Could you tell me which ls you are starting and give me some explanation how to start it please.
> 
> Sorry, I am unable to share details about the language server I am using.
> 
> Here is something else I noticed.
> 
> In the `initialize` message from the client, I see `{ "rootUri": null, "workspaceFolders": [] }` when I have GoLand opened to a project. The background is brown though which suggests to me the IDE has gotten into some [strange state](https://stackoverflow.com/questions/74246045/phpstorm-set-all-files-folders-to-brown-background-and-weird-structure).
> 
> <img width="104" alt="image" src="https://github.com/user-attachments/assets/8269b2a1-70a8-459f-aab1-27c52f9409ed">
> 
> I think this is likely the root cause of the issue...? Probably? The IDE seems to know I have a file opened at the full path but also since it's "not really in a project"

If your file doesnt belong to a project I think yiu could have strange behaviour like you have  since I have not tested this usecase.

 perhaps it cannot (or does not try to) do any path resolution and also seems to think I have a file opened "nowhere" and hence just has it at `file:///`?

**Comment by rcjsuen** [comment] 2024-10-27 11:01
@angelozerr I was able to reproduce the problem with my [open source language server](https://github.com/rcjsuen/dockerfile-language-server) with GoLand opened to the [moby/buildkit repository](https://github.com/moby/buildkit).

<img width="792" alt="image" src="https://github.com/user-attachments/assets/b400124a-3cd0-477a-9e35-468505aa56bb">

I don't have any strange "brown background" in my `Dockerfile` or the files around it so I think the system recognizes the file as being "inside a project"...?

<img width="366" alt="image" src="https://github.com/user-attachments/assets/a74bf533-8925-4dd7-b1af-2b2e16235123">

You can setup my Dockerfile language server with `npm install` and then `npm run prepublishOnly`. The language server is setup in GoLand as follows without anything for "Configuration".

<img width="857" alt="image" src="https://github.com/user-attachments/assets/54c5f846-a6ae-4439-beec-67581cc15cc8">

<img width="960" alt="image" src="https://github.com/user-attachments/assets/27b62423-f6ea-4bec-96de-1dae09eab58f">

Since the LSP logs are so big I have attached it instead of putting it directly into this comment. You can see the doubled `textDocument/didOpen` on lines 406 and 963 and the doubled `textDocument/didChange` on 12791 and 12816. Hope this helps!

[redhat-lsp4ij-issue583.txt](https://github.com/user-attachments/files/17533570/redhat-lsp4ij-issue583.txt)

**Comment by rcjsuen** [comment] 2024-10-27 11:05
My new theory is that it is related to `textDocument/semanticTokens/full` somehow. When I disable semantic highlighting support from the server's `initialize` response I cannot seem to get the issue to reproduce itself.

**Comment by angelozerr** [comment] 2024-10-27 12:14
> My new theory is that it is related to `textDocument/semanticTokens/full` somehow. When I disable semantic highlighting support from the server's `initialize` response I cannot seem to get the issue to reproduce itself.

@rcjsuen it is difficult for me to try to fix issues that we have not in our IJ Quarkus   because my current goal is to release IJ Quarkus which requires some issue to implement like https://github.com/redhat-developer/lsp4ij/pull/570

If you have time to debug and better create a PR I will be happy to review it.

If you need some help with the code base or other thing dont hesitate to ask me.

**Comment by angelozerr** [comment] 2024-11-03 05:56
> > My new theory is that it is related to `textDocument/semanticTokens/full` somehow. When I disable semantic highlighting support from the server's `initialize` response I cannot seem to get the issue to reproduce itself.
> 
> @rcjsuen it is difficult for me to try to fix issues that we have not in our IJ Quarkus   because my current goal is to release IJ Quarkus which requires some issue to implement like https://github.com/redhat-developer/lsp4ij/pull/570
> 
> If you have time to debug and better create a PR I will be happy to review it.
> 
> If you need some help with the code base or other thing dont hesitate to ask me.
> 

Have you the same problem with IJ Community?

As Goland is not free, it is difficult for me to test it.

**Comment by angelozerr** [comment] 2024-11-03 12:06
> > > My new theory is that it is related to `textDocument/semanticTokens/full` somehow. When I disable semantic highlighting support from the server's `initialize` response I cannot seem to get the issue to reproduce itself.
> > 
> > @rcjsuen it is difficult for me to try to fix issues that we have not in our IJ Quarkus   because my current goal is to release IJ Quarkus which requires some issue to implement like https://github.com/redhat-developer/lsp4ij/pull/570
> > 
> > If you have time to debug and better create a PR I will be happy to review it.
> > 
> > If you need some help with the code base or other thing dont hesitate to ask me.
> > 
> 
> Have you the same problem with IJ Community?
> 
> As Goland is not free, it is difficult for me to test it.

@rcjsuen it would be nice if you could debug lsp4ij and set a breakpoint at https://github.com/redhat-developer/lsp4ij/blob/main/src%2Fmain%2Fjava%2Fcom%2Fredhat%2Fdevtools%2Flsp4ij%2FConnectDocumentToLanguageServerSetupParticipant.java#L57 . My first feeling is that in goland this fileOpened is called twice, but perhaps I am wrong.

**Comment by rcjsuen** [comment] 2024-11-05 21:15
> Have you the same problem with IJ Community?

From a quick test just now, I was unable to reproduce it with IntelliJ IDEA 2024.2.4 (Build #IC-242.23726.103).

**Comment by angelozerr** [comment] 2024-11-05 22:01
> > Have you the same problem with IJ Community?
> 
> From a quick test just now, I was unable to reproduce it with IntelliJ IDEA 2024.2.4 (Build #IC-242.23726.103).

OK so it seems the problem comes from with goland.

**Comment by angelozerr** [comment] 2024-11-20 06:00
@rcjsuen I close the issue since you cannot reproduce it. Please reopen if youhave again the problem.

**Comment by rcjsuen** [comment] 2024-11-20 12:22
@angelozerr I am okay with that decision. I think we need to understand the exact nuance of how a JetBrains IDE operates.

**Comment by angelozerr** [comment] 2024-11-20 12:28
> @angelozerr I am okay with that decision. I think we need to understand the exact nuance of how a JetBrains IDE operates.

I agree with you. I dont like issues which are fixed but without understand.

We will see if you can reproduce it.

**Closed** 2024-11-20 14:46 UTC
