### ISSUE TITLE
textDocument/definition highlights the whole file in blue

### ISSUE THREAD

**Issue by rcjsuen** [redhat-developer/lsp4ij#644] opened 2024-11-29 18:07 UTC
**OS:** macOS Sonoma 14.4
**Editor:** GoLand 2024.1.4 Build #GO-241.18034.61, built on June 20, 2024
**LSP4IJ:** 0.8.1-20241128-131140

Sorry, I'm quite positive this is a duplicate but I can't find the original issue anymore. :(

When using `textDocument/definition` the whole file ends up getting highlighted. Can be reproduced with my [rcjsuen/dockerfile-language-server](https://github.com/rcjsuen/dockerfile-language-server) project.

https://github.com/user-attachments/assets/b1c3182a-2815-4471-ab01-7bfb26be7996

**Comment by angelozerr** [comment] 2024-11-29 18:10
It is the same issue than https://github.com/redhat-developer/lsp4ij/issues/98

It os because you have not a custom Psi. I think you are using TextMate.

@SCWells72 have you some idea how to fix it?

**Comment by rcjsuen** [comment] 2024-11-29 18:15
> It is the same issue than [#98](https://github.com/redhat-developer/lsp4ij/issues/98)

You're right. Hahaha, I saw the screenshot with nothing and closed the tab. But I see now it's a _movie_ and yes it shows the exact same behaviour. :)

> It os because you have not a custom Psi. I think you are using TextMate.

It's just a `Dockerfile` so whatever JetBrains is doing in the back I don't know.

Sorry for the noise. Feel free to close as a duplicate if desired! 🙇

**Comment by SCWells72** [comment] 2024-11-29 18:35
> It is the same issue than [#98](https://github.com/redhat-developer/lsp4ij/issues/98)
> 
> It os because you have not a custom Psi. I think you are using TextMate.
> 
> [@SCWells72](https://github.com/SCWells72) have you some idea how to fix it?

I've seen that as well. I'm not sure since the entire file is really a single PSI element instead of a true parsed PSI tree. There may be some EP from which the range of the link is derived. That would really just require some careful debugging of how link highlighting is happening.

**Comment by angelozerr** [comment] 2024-11-29 19:17
Duplicate of https://github.com/redhat-developer/lsp4ij/issues/98

**Closed by angelozerr** 2024-11-29 19:17 UTC
