### ISSUE TITLE
Keep language servers alive when all files are closed

### ISSUE THREAD

**Issue by harry-xm** [redhat-developer/lsp4ij#489] opened 2024-08-28 08:36 UTC
In a large project, it might take quite some time for rust-analyzer to initialize itself.

If someone clicked "Close All Tabs" and subsequently opens another file, the language server is restarted and I have to wait until it finishes loading.

I'm thinking of keeping the language server running until the IDE window is closed, or after an inactivity timeout. IMHO, either the user should be given an option, or plugin authors should be able to control it via some API.

_Originally posted in https://github.com/redhat-developer/lsp4ij/discussions/487_

**Comment by turkeylurkey** [comment] 2024-08-28 18:06
When you define your server `<server id="XXXlsp"` you can add the parameter `lastDocumentDisconnectedTimeout="3600"` which is an inactivity timeout.

**Comment by angelozerr** [comment] 2024-08-30 14:43
@harry-xm as @turkeylurkey suggested, you can define `lastDocumentDisconnectedTimeout="3600"` for the moment.

**Comment by angelozerr** [comment] 2024-10-02 13:53
Duplicate of https://github.com/redhat-developer/lsp4ij/issues/556 

which will be covered in 0.7.0 with https://github.com/redhat-developer/lsp4ij/pull/543

Please read https://github.com/redhat-developer/lsp4ij/issues/556#issuecomment-2388699488 and give me your feedback about the name of the method.

**Closed by angelozerr** 2024-10-02 13:53 UTC
Labels: duplicate, enhancement, api-customization
