### ISSUE TITLE
Quick Documentation command could freeze the UI

### ISSUE THREAD

**Issue by harry-xm** [redhat-developer/lsp4ij#490] opened 2024-08-28 09:56 UTC
The UI thread (EDT) should not be used to perform long-running tasks like waiting for a reply from the language server.

![Screenshot](https://github.com/user-attachments/assets/4a91f1f6-43c5-4213-8072-b80dff08a953)

See https://plugins.jetbrains.com/docs/intellij/threading-model.html:

> Operations performed on EDT must be as fast as possible to not block other events in the queue and freeze the UI. There is only one EDT in the running application.

**Comment by angelozerr** [comment] 2024-08-28 10:06
How have you reproduced this problem?

What is your suggestion? Cancel the completable future when hover is too long ?

**Comment by angelozerr** [comment] 2024-08-28 11:27
> > How have you reproduced this problem?
> 
> Open a sufficiently complex Rust project, and after rust-analyzer stops reporting progress, immediately invoke Quick Documentation. The screenshot was taken with this file: https://github.com/eunomia-bpf/eunomia-bpf/blob/291304bf415817d2f5b46a3655d9f9594b8672a6/ecli/server/src/main.rs#L97.

Thanks.

> 
> I think you could also emulate this with a language server that can delay its responses for testing.

Yes sure but I prefer using a concrete usecase.

> 
> > What is your suggestion? Cancel the completable future when hover is too long ?
> 
> See https://plugins.jetbrains.com/docs/intellij/threading-model.html. It's recommended to use background threads (BGT) for this.

I am aware about that but integrating lsp inside IJ for some features can be hard because lsp uses completablefutures and IJ doesnt provide async method like hover, inlay hint etc.

The strategy that we use is too wait for until the future gives a response.

We have an infinite loop wich waits for future is done. In this loop we call get with 5 ms and we test if progress is cancelled otherwise we continue to wait.

I have never seen some freeze  with this strategy, but now you have a usecase that I will investigate

**Comment by angelozerr** [comment] 2024-08-30 14:37
@harry-xm I have tried and I don't see some freeze?

I wonder if you have an another IJ plugin which is installed, because me I have this syntax coloration 

![image](https://github.com/user-attachments/assets/7ae3afd5-9baf-483c-8e2a-75ad31af61bb)

**Comment by angelozerr** [comment] 2024-09-02 06:38
> The UI thread (EDT) should not be used to perform long-running tasks like waiting for a reply from the language server.

I can reproduce when I do a lof of Ctrl+Q when there are a lot of $progress.

But it doesn't freeze the UI because you can type Esc or move the mouse and in this case it stops the wait of hover.

I don't know what there is this problem, but it doesn't freeze totally the UI and I have checked in debug mode that we are not in EDT context.

**Comment by angelozerr** [comment] 2024-09-02 07:01
> Do you see the "... to dump threads (X sec)" popup?

Yes but if I wait for around 20 sec, the popup is closed and everything is good.

**Closed as not planned** 2024-09-03 11:32 UTC
Labels: bug, hover
