### ISSUE TITLE
Error on IJ startup

### ISSUE THREAD

**Issue by mfortunat** [redhat-developer/lsp4ij#239] opened 2024-04-21 21:11 UTC
IJ 2024.1  Build #IU-241.14494.240, built on March 28, 2024
LSP4IJ 0.0.1-20240419-012629
--- --- --- --- --- ---

By simply starting IJ, with the focus on an `application.properties` tab, shows this error:
--- --- --- --- --- --- 

Error while consuming 'textDocument/inlayHint' with language server 'Tools for MicroProfile'

org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:262)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by mfortunat** [comment] 2024-04-21 22:21
This also happens when running IJ with the focus on a Java code tab and switching to the 'application.properties' tab

**Comment by angelozerr** [comment] 2024-04-21 23:06
@mfortunat  at first, your error comes from the language server and you can disable it https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#feedback if you wish.

The language server error was hidden before and now by default you can see them and disable it if you wish.

You should see detail error in the LSP console. I suspect that you have this error:

`Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletionStage.toCompletableFuture()" because the return value of "java.util.function.Function.apply(Object)" is null`

which is a bug from MicroProfile LS (it should throws a better error which mention that the open document was not done while calling inlay hint) 

I think LSP4IJ should takecare of this problem too https://github.com/redhat-developer/lsp4ij/issues/173

**Comment by mfortunat** [comment] 2024-04-22 00:07
👍

**Comment by angelozerr** [comment] 2024-04-22 17:32
Duplicate of https://github.com/redhat-developer/lsp4ij/issues/173

**Closed by angelozerr** 2024-04-22 17:32 UTC
Labels: bug, duplicate
